services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile

    image: giveaway-mongodb:8
    container_name: giveaway-mongodb
    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword

    command:
      [
        "mongod",
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--keyFile",
        "/etc/mongodb-keyfile"
      ]

    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: